### ISSUE TITLE
A request that should return an HTTP 405 instead returns status 0

### ISSUE THREAD

**Issue by jmlsf** [r0man/cljs-http#112] opened 2018-01-18 00:02 UTC
If I run this simple code:

```clojure
(defn testcall [] (go (prn (<! (http/post "http://www.google.com")))))
```

I get this response:

```clojure
{:status 0,
 :success false,
 :body "",
 :headers {},
 :trace-redirects ["http://www.google.com" "http://www.google.com"],
 :error-code :http-error,
 :error-text " [0]"}
```

This result seems incorrect in several respects:
1.  We should be getting an HTTP 405.
2.  Even if there were some kind of network error, the GCL documentation states that we should be getting a `:status -1`, not a `:status 0`.
3.  What's up with that `:error-text " [0]"`?  That looks like some kind of interop error.

**Comment by leourbina** [comment] 2018-01-19 05:32
@jmlsf An HTTP status of 0 means that the request failed and received 0 bytes as a response. If you look at your console you'll probably find something like this

![developer_tools_-_http___localhost_8080_](https://user-images.githubusercontent.com/434020/35136096-4df8133e-fc96-11e7-9c97-069a7f079e1e.png)

In this case the request failed because Google does not have CORS headers on google.com (probably a good thing). So even though you can POST to it from curl and other similar clients, doing so from the browser will fail for security reasons. Hopefully that helps.

**Comment by jmlsf** [comment] 2018-01-19 06:01
What about the `:error-text`?  Is that normal?

**Comment by leourbina** [comment] 2018-01-19 06:03
Yep. Just look at your network tab and you'll see that the request was rejected. You're not getting anything back from the server. Consider closing this ticket as this is not a bug.

**Closed** 2018-01-19 06:34 UTC
