### ISSUE TITLE
Misplaced function annotation warning in jsonp.js

### ISSUE THREAD

**Issue by sthomp** [r0man/cljs-http#70] opened 2015-07-30 15:56 UTC
Getting the following compiler warning after using cljs-http 0.1.35 in my project:

```
Jul 30, 2015 11:53:55 AM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: file:/Users/xxxxxx/.m2/repository/org/clojure/google-closure-library/0.0-20140718-946a7d39/google-closure-library-0.0-20140718-946a7d39.jar!/goog/net/jsonp.js:269: WARNING - Misplaced function annotation.
  return function(var_args) {
  ^

Jul 30, 2015 11:53:55 AM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 0 error(s), 1 warning(s)
```

Is this a known warning?

**Comment by jindrichmynarz** [comment] 2015-12-16 16:26
This is a warning caused by Google Closure. Updating cljs-http to the current version of Clojurescript (1.7.170) including a more recent version of Google Closure resolves this issue.

**Comment by r0man** [comment] 2015-12-17 11:27
Fixed in master.

**Closed by r0man** 2015-12-17 11:27 UTC
